-- Create the orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    owner_name TEXT,
    phone TEXT,
    check_in DATE,
    check_out DATE,
    dog_name TEXT,
    dog_age TEXT,
    dog_breed TEXT, -- Note: App uses this column to store dog size
    neutered TEXT,
    dog_temperament TEXT,
    notes TEXT,
    status TEXT DEFAULT 'ממתין', -- Options: 'ממתין', 'מאושר', 'בוטל'
    admin_note TEXT,
    price_per_day NUMERIC DEFAULT 130,
    is_arrived BOOLEAN DEFAULT FALSE,
    is_departed BOOLEAN DEFAULT FALSE
);

-- Enable Row Level Security (RLS)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow full access for the application
-- Note: The application uses the anon key for all operations including admin functions
CREATE POLICY "Allow broad access to orders"
ON orders
FOR ALL
TO anon
USING (true)
WITH CHECK (true);
